// バイブコーディング (AI生成アプリ) 系の脆弱性を検出。
// - クライアント露出シークレット (API key / token 等)
// - 露出パス (.env / .git / package.json 等)
// - AI 生成コメント / Supabase 直叩きパターン

import { chromium } from "playwright";
import { isUrlInScope } from "@/lib/scope";
import { safeJsonParse } from "@/lib/json";
import { maskBody } from "@/lib/mask";
import { makeScanCtx, createScanFinding, findExistingScanFinding } from "@/lib/scan-adapter";

const SECRET_PATTERNS: Array<{ name: string; re: RegExp; category: string; severity: "critical" | "high" | "medium"; tier: string }> = [
  { name: "Stripe Live Secret Key", re: /\bsk_live_[A-Za-z0-9]{20,}/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "Stripe Test Secret Key", re: /\bsk_test_[A-Za-z0-9]{20,}/, category: "credentials", severity: "high", tier: "Medium-High" },
  { name: "Stripe Publishable Live Key", re: /\bpk_live_[A-Za-z0-9]{20,}/, category: "info_leak", severity: "medium", tier: "Low-Medium" },
  { name: "Supabase Service Role Key", re: /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{30,}/, category: "credentials", severity: "high", tier: "High" },
  { name: "Firebase API Key (Web)", re: /\bAIza[0-9A-Za-z_-]{35}\b/, category: "info_leak", severity: "medium", tier: "Low-Medium" },
  { name: "AWS Access Key ID", re: /\b(AKIA|ASIA)[0-9A-Z]{16}\b/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "AWS Secret Access Key (in close proximity to key id)", re: /aws_secret_access_key\s*[:=]\s*["']?[A-Za-z0-9/+=]{40}["']?/i, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "GitHub Personal Access Token", re: /\bghp_[A-Za-z0-9]{36}\b/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "GitHub Fine-grained Token", re: /\bgithub_pat_[A-Za-z0-9_]{60,}/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "OpenAI API Key", re: /\bsk-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "Anthropic API Key", re: /\bsk-ant-[A-Za-z0-9_-]{40,}/, category: "credentials", severity: "critical", tier: "Critical" },
  { name: "Google OAuth Client Secret", re: /\bGOCSPX-[A-Za-z0-9_-]{20,}/, category: "credentials", severity: "high", tier: "High" },
  { name: "Sendgrid API Key", re: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/, category: "credentials", severity: "high", tier: "High" },
  { name: "Twilio Auth Token", re: /\bSK[a-f0-9]{32}\b/, category: "credentials", severity: "high", tier: "High" },
  { name: "Slack Webhook URL", re: /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]{8,}\/B[A-Z0-9]{8,}\/[A-Za-z0-9]{20,}/, category: "credentials", severity: "high", tier: "Medium-High" },
  { name: "Discord Webhook URL", re: /https:\/\/(?:discord|discordapp)\.com\/api\/webhooks\/\d+\/[A-Za-z0-9_-]{40,}/, category: "credentials", severity: "medium", tier: "Low-Medium" },
  { name: "Generic Bearer in JS", re: /Bearer\s+[A-Za-z0-9_\-\.]{30,}/, category: "credentials", severity: "high", tier: "High" }
];

const VIBE_DEBUG_PATHS = [
  "/.env", "/.env.local", "/.env.production", "/.env.development",
  "/.git/config", "/.git/HEAD", "/.git/index",
  "/package.json", "/package-lock.json",
  "/next.config.js", "/next.config.mjs", "/vite.config.js", "/vite.config.ts",
  "/tsconfig.json",
  "/.well-known/apollo/server-health",
  "/api/debug", "/api/_debug", "/api/admin/debug", "/api/test", "/api/_test", "/api/dev", "/api/_dev", "/api/_internal", "/api/internal",
  "/api/health", "/api/_health", "/admin/", "/admin/login", "/admin/api",
  "/api/v1/users", "/api/v1/admin", "/api/users", "/api/admin",
  "/server-status", "/phpinfo.php", "/.DS_Store",
  "/sitemap.xml", "/robots.txt",
  "/api/graphql", "/graphql", "/api/trpc/_app", "/_next/static/chunks/main-app.js"
];

const VIBE_AI_HINTS = [
  /\/\/\s*(?:TODO|FIXME|HACK|XXX)\s*:?.*?(?:add\s+auth|implement\s+later|skip\s+auth|disable.+auth|temporary)/i,
  /\/\/\s*Generated by (?:Claude|GPT|Copilot|Cursor|Bolt|v0|Lovable|Replit AI|Devin)/i,
  /\/\/\s*(?:AI|GPT|Claude)\s*(?:assistant|generated|wrote)/i,
  /console\.log\(\s*["']DEBUG\b/,
  /\bif\s*\(\s*(?:process\.env\.NODE_ENV|env)\s*===?\s*["']development["']\s*\)\s*\{[^}]*?(?:bypass|skip|disable)\b/i
];

const VIBE_SUPABASE_RLS_HINTS = /supabase\.from\(["'][^"']+["']\)\.(?:select|insert|update|delete)\(/;

async function fetchAnonymous(url: string): Promise<{ status: number; body: string; headers: Record<string, string | string[] | undefined> }> {
  const browser = await chromium.launch({ headless: true });
  try {
    const context = await browser.newContext({ ignoreHTTPSErrors: true });
    const page = await context.newPage();
    const res = await page.request.fetch(url, { method: "GET", failOnStatusCode: false, timeout: 8000 });
    const body = await res.text().catch(() => "");
    const headers = res.headers();
    await context.close();
    return { status: res.status(), body, headers };
  } finally {
    await browser.close();
  }
}

function isHtmlResponse(body: string, headers: Record<string, string | string[] | undefined>): boolean {
  const ct = ((headers["content-type"] ?? "") as string).toLowerCase();
  if (ct.includes("text/html")) return true;
  const trimmed = body.trimStart();
  return /^<!doctype\s+html/i.test(trimmed) || /^<html[\s>]/i.test(trimmed.slice(0, 200));
}

function bodyMatchesExpected(path: string, body: string): { ok: boolean; reason?: string } {
  if (path === "/sitemap.xml" || path === "/robots.txt") {
    return { ok: false, reason: "public-by-design (not a finding)" };
  }
  if (/_next\/static/.test(path)) {
    return { ok: false, reason: "intended public static asset" };
  }
  if (/^\/\.env(\..+)?$/i.test(path)) {
    const envLikeLines = body.split(/\r?\n/).filter((l) => /^[A-Z_][A-Z0-9_]*\s*=/.test(l.trim()));
    return envLikeLines.length >= 2
      ? { ok: true }
      : { ok: false, reason: "body does not contain multiple KEY=value env lines" };
  }
  if (path === "/.git/HEAD") {
    return /^ref:\s*refs\//m.test(body)
      ? { ok: true }
      : { ok: false, reason: "body does not look like git HEAD ref" };
  }
  if (path === "/.git/index") {
    return body.startsWith("DIRC")
      ? { ok: true }
      : { ok: false, reason: "body does not start with DIRC magic" };
  }
  if (path === "/.git/config") {
    return /\[(?:core|remote\s+|branch\s+)/.test(body)
      ? { ok: true }
      : { ok: false, reason: "body does not look like git config ini" };
  }
  if (/\/(package(?:-lock)?|tsconfig)\.json$/i.test(path)) {
    const trimmed = body.trimStart();
    if (!trimmed.startsWith("{")) return { ok: false, reason: "body is not JSON" };
    try {
      const obj = JSON.parse(trimmed);
      if (path.endsWith("/package.json") && (typeof obj.name !== "string" || !obj.dependencies && !obj.scripts)) {
        return { ok: false, reason: "JSON does not look like package.json" };
      }
      if (path.endsWith("/package-lock.json") && typeof obj.lockfileVersion !== "number" && !obj.dependencies && !obj.packages) {
        return { ok: false, reason: "JSON does not look like package-lock.json" };
      }
      if (path.endsWith("/tsconfig.json") && !obj.compilerOptions && !obj.extends && !obj.include) {
        return { ok: false, reason: "JSON does not look like tsconfig.json" };
      }
      return { ok: true };
    } catch { return { ok: false, reason: "body is not valid JSON" }; }
  }
  if (/\/(next|vite|webpack)\.config\.(js|ts|mjs|cjs)$/i.test(path)) {
    return /\b(?:module\.exports|export\s+default|defineConfig|require\s*\(|import\s+)/.test(body)
      ? { ok: true }
      : { ok: false, reason: "body does not look like JS/TS config module" };
  }
  if (/server-health|\/api\/(?:health|_health)$/.test(path)) {
    const trimmed = body.trimStart();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      try { JSON.parse(trimmed); return { ok: true }; } catch { return { ok: false, reason: "invalid JSON" }; }
    }
    return { ok: false, reason: "health endpoint returned non-JSON" };
  }
  if (path === "/server-status") {
    return /Apache Server Status|Server Version|Total accesses/i.test(body)
      ? { ok: true }
      : { ok: false, reason: "not Apache server-status format" };
  }
  if (path === "/phpinfo.php") {
    return /<title>phpinfo\(\)<\/title>|PHP Version|System\s+Linux/i.test(body)
      ? { ok: true }
      : { ok: false, reason: "no phpinfo signature" };
  }
  if (path === "/.DS_Store") {
    return /\bBud1\b/.test(body.slice(0, 32))
      ? { ok: true }
      : { ok: false, reason: "no .DS_Store binary signature" };
  }
  if (/^\/admin\/?(?:login)?$/i.test(path)) {
    return { ok: false, reason: "admin login page is intended UI" };
  }
  if (/^\/admin\/api/i.test(path)) {
    const trimmed = body.trimStart();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) return { ok: true };
    return { ok: false, reason: "admin api returned non-JSON (likely SPA fallback)" };
  }
  if (/^\/api\//.test(path)) {
    const trimmed = body.trimStart();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) return { ok: true };
    return { ok: false, reason: "API endpoint returned non-JSON (likely SPA fallback)" };
  }
  if (/graphql|trpc/.test(path)) {
    if (/__schema|__type|"errors"|"data"/.test(body)) return { ok: true };
    return { ok: false, reason: "GraphQL endpoint did not return GQL response" };
  }
  return { ok: true };
}

async function createOrSkipFinding(scanId: string, args: {
  type: string;
  target: string;
  impact: string;
  inScopeReason: string;
  evidence: string;
  requestResponseDiff: string;
  reproductionSteps: string;
  category: string;
  severity: "critical" | "high" | "medium" | "low";
}) {
  const sevLabel = args.severity === "critical" ? "Critical" : args.severity === "high" ? "High" : args.severity === "medium" ? "Medium" : "Low";
  const taggedType = `${args.type} [${sevLabel}]`;
  const existing = await findExistingScanFinding(scanId, taggedType, args.target);
  if (existing) return null;

  await createScanFinding(scanId, {
    type: taggedType,
    target: args.target,
    severity: args.severity,
    impact: args.impact,
    inScopeReason: args.inScopeReason,
    evidence: args.evidence,
    requestResponseDiff: args.requestResponseDiff,
    reproductionSteps: args.reproductionSteps,
    aiWorthSending: args.severity === "critical" ? "AI生成アプリの典型的な抜けで、重大な漏洩に直結する可能性がございます。" : "バイブコーディング由来の典型的な抜けです。",
    bountyLikelihood: args.severity === "critical" ? "very_high" : args.severity === "high" ? "high" : "medium",
    recommendedAction: args.severity === "critical" ? "report_now" : "manual_verify"
  });
  return true;
}

export async function runClientSecretScan(scanId: string, targetUrl: string) {
  const program = makeScanCtx(scanId, targetUrl);
  const base = new URL(targetUrl).origin;
  let count = 0;
  const seen = new Set<string>();

  // Fetch main page and JS bundles
  const pageSources: Array<{ url: string; body: string; contentType: string }> = [];
  try {
    const mainPage = await fetchAnonymous(targetUrl);
    if (mainPage.status === 200) {
      pageSources.push({ url: targetUrl, body: mainPage.body.slice(0, 200000), contentType: ((mainPage.headers["content-type"] ?? "") as string) });
      // Find JS bundle URLs
      const scriptMatches = mainPage.body.matchAll(/<script[^>]*src=["']([^"']+\.js[^"']*)["']/gi);
      for (const m of scriptMatches) {
        try {
          const jsUrl = new URL(m[1], base).toString();
          if (isUrlInScope(program, jsUrl).allowed && !seen.has(jsUrl)) {
            seen.add(jsUrl);
            const jsRes = await fetchAnonymous(jsUrl);
            if (jsRes.status === 200) {
              pageSources.push({ url: jsUrl, body: jsRes.body.slice(0, 200000), contentType: "application/javascript" });
            }
            if (pageSources.length >= 6) break;
          }
        } catch { /* ignore */ }
      }
    }
  } catch { /* ignore */ }

  for (const source of pageSources) {
    for (const pattern of SECRET_PATTERNS) {
      const match = source.body.match(pattern.re);
      if (!match) continue;
      const key = `${pattern.name}|${match[0].slice(0, 12)}`;
      if (seen.has(key)) continue;
      seen.add(key);

      const created = await createOrSkipFinding(scanId, {
        type: `クライアント露出シークレット: ${pattern.name}`,
        target: `GET ${source.url}`,
        impact: `${pattern.name} らしき値がクライアントに配信されるアセットに埋め込まれております。バイブコーディング(AI生成アプリ)で頻発する典型的な漏洩パターンでございます。`,
        inScopeReason: `収集済み許可ドメイン内アセット`,
        evidence: `url=${source.url}, pattern=${pattern.name}, sampleHash=${match[0].slice(0, 8)}…`,
        requestResponseDiff: maskBody(source.contentType, JSON.stringify({
          pattern: pattern.name,
          sampleStart: match[0].slice(0, 12) + "…",
          contextSnippet: source.body.slice(Math.max(0, (match.index ?? 0) - 80), Math.min(source.body.length, (match.index ?? 0) + match[0].length + 80))
        }, null, 2)),
        reproductionSteps: `1. ${source.url} を取得\n2. レスポンス本文に ${pattern.name} の典型パターンが含まれていることを確認\n3. 値の一部 (${match[0].slice(0, 6)}…) で grep して同じ値であることを確認`,
        category: pattern.category,
        severity: pattern.severity
      });
      if (created) count++;
    }
  }
  return count;
}

export async function runVibeDebugPathScan(scanId: string, targetUrl: string) {
  const program = makeScanCtx(scanId, targetUrl);
  const allowed = safeJsonParse<string[]>(program.allowedDomains, []);
  let count = 0;
  const base = new URL(targetUrl).origin;
  const targetHost = new URL(targetUrl).hostname;

  // Build list of hosts to probe
  const hosts: string[] = [targetHost];
  for (const domain of allowed) {
    const cleaned = domain.replace(/^\*\./, "").replace(/^https?:\/\//, "").replace(/\/.*$/, "");
    if (cleaned && cleaned !== targetHost && !hosts.includes(cleaned)) {
      hosts.push(cleaned);
    }
  }

  for (const host of hosts.slice(0, 5)) {
    const hostBase = `https://${host}`;
    for (const path of VIBE_DEBUG_PATHS.slice(0, 24)) {
      const url = `${hostBase}${path}`;
      if (!isUrlInScope(program, url).allowed && !url.startsWith(base)) continue;
      try {
        const result = await fetchAnonymous(url);
        if (result.status !== 200 || result.body.length < 50) continue;

        if (isHtmlResponse(result.body, result.headers)) continue;

        const match = bodyMatchesExpected(path, result.body);
        if (!match.ok) continue;

        let category = "info_leak";
        let severity: "critical" | "high" | "medium" = "medium";
        if (/\.env|\.git\/config|aws_secret|api_key.*=/i.test(result.body) || /^DATABASE_URL=|^OPENAI_API_KEY=/m.test(result.body)) {
          category = "credentials";
          severity = "critical";
        } else if (/admin|debug|internal|_dev/i.test(path) && /[\{\[]/.test(result.body)) {
          category = "admin_data";
          severity = "high";
        }

        const created = await createOrSkipFinding(scanId, {
          type: `バイブコーディング系 露出パス: ${path}`,
          target: `GET ${url}`,
          impact: `AI生成アプリで頻出する露出パス ${path} が公開されております。body 内容も期待形式と一致 (HTML fallback ではない) ことを確認済み。`,
          inScopeReason: `許可ドメイン直下の公開パス (body content verified)`,
          evidence: `status=${result.status}, bodySize=${result.body.length}, contentType=${result.headers["content-type"] ?? "unknown"}`,
          requestResponseDiff: JSON.stringify({ path, status: result.status, bodyPreview: result.body.slice(0, 1500) }, null, 2),
          reproductionSteps: `1. シークレットウィンドウまたは curl で ${url} に GET\n2. ${result.status} で応答が返り、${path} の中身が露出していることを確認`,
          category,
          severity
        });
        if (created) count++;
      } catch { /* skip */ }
    }
  }
  return count;
}

export async function runVibeAiCommentScan(scanId: string, targetUrl: string) {
  const program = makeScanCtx(scanId, targetUrl);
  const base = new URL(targetUrl).origin;
  let count = 0;

  // Fetch JS bundles from main page
  const jsUrls: string[] = [];
  try {
    const mainPage = await fetchAnonymous(targetUrl);
    const scriptMatches = mainPage.body.matchAll(/<script[^>]*src=["']([^"']+\.js[^"']*)["']/gi);
    for (const m of scriptMatches) {
      try {
        const jsUrl = new URL(m[1], base).toString();
        if (isUrlInScope(program, jsUrl).allowed) jsUrls.push(jsUrl);
        if (jsUrls.length >= 10) break;
      } catch { /* ignore */ }
    }
  } catch { /* ignore */ }

  for (const jsUrl of jsUrls.slice(0, 10)) {
    try {
      const res = await fetchAnonymous(jsUrl);
      if (res.status !== 200) continue;
      const body = res.body.slice(0, 200000);
      const hits: string[] = [];
      for (const re of VIBE_AI_HINTS) {
        const m = body.match(re);
        if (m) hits.push(m[0].slice(0, 120));
      }
      if (VIBE_SUPABASE_RLS_HINTS.test(body)) hits.push("Supabase直叩き呼び出し (RLS未設定の可能性)");
      if (hits.length === 0) continue;

      const created = await createOrSkipFinding(scanId, {
        type: `バイブコーディング由来コメント/コードパターン検出`,
        target: `GET ${jsUrl}`,
        impact: `AI生成アプリでよく見られる「認可TODO残し」「Supabase直叩き」「生成元コメント」などが配信アセットに含まれております。深掘り調査の優先度が高い候補です。`,
        inScopeReason: `収集済み許可ドメイン内のクライアント側アセット`,
        evidence: `url=${jsUrl}, hints=${hits.length}`,
        requestResponseDiff: JSON.stringify({ patternHits: hits }, null, 2),
        reproductionSteps: `1. ${jsUrl} を取得\n2. レスポンス本文を grep し、${hits.slice(0, 3).join(" / ")} 等のパターンが含まれていることを確認\n3. 該当箇所周辺のロジックに認可漏れがないか深掘り`,
        category: "info_leak",
        severity: "medium"
      });
      if (created) count++;
    } catch { /* skip */ }
  }
  return count;
}

export async function runComprehensiveVibeChecks(scanId: string, targetUrl: string) {
  const secret = await runClientSecretScan(scanId, targetUrl).catch(() => 0);
  const debug = await runVibeDebugPathScan(scanId, targetUrl).catch(() => 0);
  const aiHints = await runVibeAiCommentScan(scanId, targetUrl).catch(() => 0);
  return { secret, debug, aiHints };
}
